# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ryan Heathcote
tagline:             'Engineer. Teacher. Dreamer.'
description:         'This is where I collect the many profound and deep brain things that happen inside my head.'
url:                 http://ryanheathcote.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ryan Heathcote
  url:               http://ryanheathcote.com/
  email:             ryan.m.heathcote@gmail.com
